name: m2-actions-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-18.04
    name: 'build m2'
    services:
      mysql:
        image: docker://mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3106:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://madit512/magento2-elasticsearch:5.6
        ports:
          - 9200:9200
      rabbitmq:
        image: docker://rabbitmq:3.6.6-alpine
        env:
          RABBITMQ_DEFAULT_USER: "magento"
          RABBITMQ_DEFAULT_PASS: "magento"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - 5672:5672

    steps:
    - uses: actions/checkout@master
    - name: 'launch magento2 build'
      if: always()
      uses: MAD-I-T/magento-actions@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.1'
        process: 'build'
        elasticsuite: 1

  magento2-integration-test:
    runs-on: ubuntu-18.04
    name: 'integration test m2'
    services:
      mysql:
        image: docker://mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "123123q"
          MYSQL_DATABASE: "magento_integration_tests"
        ports:
          - 3106:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://madit512/magento2-elasticsearch:5.6
        ports:
          - 9200:9200
      rabbitmq:
        image: docker://rabbitmq:3.6.6-alpine
        env:
          RABBITMQ_DEFAULT_USER: "guest"
          RABBITMQ_DEFAULT_PASS: "guest"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - 5672:5672
    steps:
    - uses: actions/checkout@master
    - name: 'launch magento2 integration test'
      if: always()
      uses: MAD-I-T/magento-actions@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.1'
        process: 'integration-test'
        elasticsuite: 1
