name: m2-actions-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-18.04
    name: 'build m2'
    services:
      mysql:
        image: docker://mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3106:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://madit512/magento2-elasticsearch:5.6
        ports:
          - 9200:9200
      rabbitmq:
        image: docker://rabbitmq:3.6.6-alpine
        env:
          RABBITMQ_DEFAULT_USER: "magento"
          RABBITMQ_DEFAULT_PASS: "magento"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - 5672:5672

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: 'launch security scanner files'
      if: always()
      uses: MAD-I-T/magento-actions@v2.0
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.1'
        process: 'security-scan-files'
    - name: 'launch security scanner modules'
      if: always()
      uses: MAD-I-T/magento-actions@v2.0
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.2'
        process: 'security-scan-modules'
        elasticsearch: 1
    - name: 'launch magento2 unit test'
      if: always()
      uses: MAD-I-T/magento-actions@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.1'
        process: 'unit-test'
        elasticsearch: 1
    - name: 'launch magento2 static test'
      if: always()
      uses: MAD-I-T/magento-actions@v2.0
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.1'
        process: 'static-test'
        elasticsuite: 1

    - name: 'phpcs testing'
      if: always()
      uses: MAD-I-T/magento-actions@3.7
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.1'
        process: 'phpcs-test'
        extension: 'Magento/CatalogSearch'
        standard: 'Magento2'
    - name: 'launch magento2 build'
      if: always()
      uses: MAD-I-T/magento-actions@v2.0
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.1'
        process: 'build'
        elasticsuite: 1
    - name: 'launch magento2 integration test'
      if: ${{false}}
      uses: MAD-I-T/magento-actions@v2.0
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.1'
        process: 'integration-test'
        elasticsuite: 1
